CREATE PROC [dbo].[FI_SP_ListaBeneficiarios]
	@IDCLIENTE BIGINT
AS
BEGIN
	SELECT ID, SUBSTRING(CPF,1,3) + '.' + SUBSTRING(CPF,4,3) + '.' + SUBSTRING(CPF,7,3) + '-' + SUBSTRING(CPF,10,2) AS CPF, NOME, IDCLIENTE FROM [dbo].[BENEFICIARIOS] WHERE IDCLIENTE = @IDCLIENTE
END