CREATE PROC [dbo].[FI_SP_IncBeneficiario]
    @NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (11),
	@IDCLIENTE     BIGINT
AS
BEGIN

	INSERT INTO [dbo].[BENEFICIARIOS] (CPF, NOME, IDCLIENTE) 
	VALUES ( @CPF, @NOME, @IDCLIENTE )

	SELECT SCOPE_IDENTITY()
		
END